[2021-12-24 11:44:32,404] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2021-12-24T11:37:50.453196+00:00 [queued]>
[2021-12-24 11:44:32,647] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: classification.apply_model 2021-12-24T11:37:50.453196+00:00 [queued]>
[2021-12-24 11:44:32,661] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-12-24 11:44:32,683] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-12-24 11:44:32,698] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-12-24 11:44:32,872] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): apply_model> on 2021-12-24T11:37:50.453196+00:00
[2021-12-24 11:44:32,970] {standard_task_runner.py:52} INFO - Started process 54 to run task
[2021-12-24 11:44:33,040] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'classification', 'apply_model', '2021-12-24T11:37:50.453196+00:00', '--job-id', '155', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/classification.py', '--cfg-path', '/tmp/tmpfijo344c', '--error-file', '/tmp/tmpfiy09cx7']
[2021-12-24 11:44:33,079] {standard_task_runner.py:77} INFO - Job 155: Subtask apply_model
[2021-12-24 11:44:33,584] {logging_mixin.py:104} INFO - Running <TaskInstance: classification.apply_model 2021-12-24T11:37:50.453196+00:00 [running]> on host 0d76f33c6135
[2021-12-24 11:44:34,148] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=classification
AIRFLOW_CTX_TASK_ID=apply_model
AIRFLOW_CTX_EXECUTION_DATE=2021-12-24T11:37:50.453196+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-24T11:37:50.453196+00:00
[2021-12-24 11:44:57,224] {logging_mixin.py:104} WARNING - /usr/local/lib/python3.6/site-packages/PIL/Image.py:976 UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
[2021-12-24 11:45:05,628] {taskinstance.py:1455} ERROR - image file is truncated (6 bytes not processed)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/classification.py", line 104, in apply_dl_model
    img = image.load_img(os.path.join(process_dir,filename), target_size=(64, 64))
  File "/usr/local/lib/python3.6/site-packages/keras/preprocessing/image.py", line 314, in load_img
    target_size=target_size, interpolation=interpolation)
  File "/usr/local/lib/python3.6/site-packages/keras_preprocessing/image/utils.py", line 138, in load_img
    img = img.resize(width_height_tuple, resample)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 1989, in resize
    self.load()
  File "/usr/local/lib/python3.6/site-packages/PIL/ImageFile.py", line 250, in load
    "image file is truncated "
OSError: image file is truncated (6 bytes not processed)
[2021-12-24 11:45:05,688] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=classification, task_id=apply_model, execution_date=20211224T113750, start_date=20211224T114432, end_date=20211224T114505
[2021-12-24 11:45:05,815] {local_task_job.py:146} INFO - Task exited with return code 1
